// flow-typed signature: 5087f3e6a7536fab70999cbda0bdfa17
// flow-typed version: <<STUB>>/babel-plugin-transform-semantic-ui-react-imports_v^1.3.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-semantic-ui-react-imports'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-semantic-ui-react-imports' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-transform-semantic-ui-react-imports/index' {
  declare module.exports: $Exports<'babel-plugin-transform-semantic-ui-react-imports'>;
}
declare module 'babel-plugin-transform-semantic-ui-react-imports/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-semantic-ui-react-imports'>;
}
