// flow-typed signature: 074c2fb795b5789a3e05b7c47e0fd8f8
// flow-typed version: <<STUB>>/lodash.throttle_v^4.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.throttle/index' {
  declare module.exports: $Exports<'lodash.throttle'>;
}
declare module 'lodash.throttle/index.js' {
  declare module.exports: $Exports<'lodash.throttle'>;
}
