// flow-typed signature: 51641f6bdd0a6bcf4f628c6aa388f113
// flow-typed version: <<STUB>>/popmotion_v^8.3.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'popmotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'popmotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'popmotion/dist/popmotion.es' {
  declare module.exports: any;
}

declare module 'popmotion/dist/popmotion.global.min' {
  declare module.exports: any;
}

declare module 'popmotion/dist/popmotion' {
  declare module.exports: any;
}

declare module 'popmotion/lib/action/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/action/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/action/vector' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/decay/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/decay/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/every-frame/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/keyframes/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/keyframes/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/physics/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/physics/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/spring/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/spring/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/timeline/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/timeline/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/tween/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/tween/scrubber' {
  declare module.exports: any;
}

declare module 'popmotion/lib/animations/tween/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/calc' {
  declare module.exports: any;
}

declare module 'popmotion/lib/chainable/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/chainable/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/chain' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/composite' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/crossfade' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/delay' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/merge' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/multi' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/parallel' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/schedule' {
  declare module.exports: any;
}

declare module 'popmotion/lib/compositors/stagger' {
  declare module.exports: any;
}

declare module 'popmotion/lib/easing' {
  declare module.exports: any;
}

declare module 'popmotion/lib/global-xl' {
  declare module.exports: any;
}

declare module 'popmotion/lib/global' {
  declare module.exports: any;
}

declare module 'popmotion/lib/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/input/listen/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/input/listen/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/input/multitouch/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/input/pointer/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/input/pointer/mouse' {
  declare module.exports: any;
}

declare module 'popmotion/lib/input/pointer/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/input/pointer/utils' {
  declare module.exports: any;
}

declare module 'popmotion/lib/observer/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/observer/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/reactions/index' {
  declare module.exports: any;
}

declare module 'popmotion/lib/reactions/multicast' {
  declare module.exports: any;
}

declare module 'popmotion/lib/reactions/types' {
  declare module.exports: any;
}

declare module 'popmotion/lib/reactions/value' {
  declare module.exports: any;
}

declare module 'popmotion/lib/transformers' {
  declare module.exports: any;
}

declare module 'popmotion/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'popmotion/dist/popmotion.es.js' {
  declare module.exports: $Exports<'popmotion/dist/popmotion.es'>;
}
declare module 'popmotion/dist/popmotion.global.min.js' {
  declare module.exports: $Exports<'popmotion/dist/popmotion.global.min'>;
}
declare module 'popmotion/dist/popmotion.js' {
  declare module.exports: $Exports<'popmotion/dist/popmotion'>;
}
declare module 'popmotion/lib/action/index.js' {
  declare module.exports: $Exports<'popmotion/lib/action/index'>;
}
declare module 'popmotion/lib/action/types.js' {
  declare module.exports: $Exports<'popmotion/lib/action/types'>;
}
declare module 'popmotion/lib/action/vector.js' {
  declare module.exports: $Exports<'popmotion/lib/action/vector'>;
}
declare module 'popmotion/lib/animations/decay/index.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/decay/index'>;
}
declare module 'popmotion/lib/animations/decay/types.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/decay/types'>;
}
declare module 'popmotion/lib/animations/every-frame/index.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/every-frame/index'>;
}
declare module 'popmotion/lib/animations/keyframes/index.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/keyframes/index'>;
}
declare module 'popmotion/lib/animations/keyframes/types.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/keyframes/types'>;
}
declare module 'popmotion/lib/animations/physics/index.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/physics/index'>;
}
declare module 'popmotion/lib/animations/physics/types.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/physics/types'>;
}
declare module 'popmotion/lib/animations/spring/index.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/spring/index'>;
}
declare module 'popmotion/lib/animations/spring/types.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/spring/types'>;
}
declare module 'popmotion/lib/animations/timeline/index.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/timeline/index'>;
}
declare module 'popmotion/lib/animations/timeline/types.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/timeline/types'>;
}
declare module 'popmotion/lib/animations/tween/index.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/tween/index'>;
}
declare module 'popmotion/lib/animations/tween/scrubber.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/tween/scrubber'>;
}
declare module 'popmotion/lib/animations/tween/types.js' {
  declare module.exports: $Exports<'popmotion/lib/animations/tween/types'>;
}
declare module 'popmotion/lib/calc.js' {
  declare module.exports: $Exports<'popmotion/lib/calc'>;
}
declare module 'popmotion/lib/chainable/index.js' {
  declare module.exports: $Exports<'popmotion/lib/chainable/index'>;
}
declare module 'popmotion/lib/chainable/types.js' {
  declare module.exports: $Exports<'popmotion/lib/chainable/types'>;
}
declare module 'popmotion/lib/compositors/chain.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/chain'>;
}
declare module 'popmotion/lib/compositors/composite.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/composite'>;
}
declare module 'popmotion/lib/compositors/crossfade.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/crossfade'>;
}
declare module 'popmotion/lib/compositors/delay.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/delay'>;
}
declare module 'popmotion/lib/compositors/merge.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/merge'>;
}
declare module 'popmotion/lib/compositors/multi.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/multi'>;
}
declare module 'popmotion/lib/compositors/parallel.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/parallel'>;
}
declare module 'popmotion/lib/compositors/schedule.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/schedule'>;
}
declare module 'popmotion/lib/compositors/stagger.js' {
  declare module.exports: $Exports<'popmotion/lib/compositors/stagger'>;
}
declare module 'popmotion/lib/easing.js' {
  declare module.exports: $Exports<'popmotion/lib/easing'>;
}
declare module 'popmotion/lib/global-xl.js' {
  declare module.exports: $Exports<'popmotion/lib/global-xl'>;
}
declare module 'popmotion/lib/global.js' {
  declare module.exports: $Exports<'popmotion/lib/global'>;
}
declare module 'popmotion/lib/index.js' {
  declare module.exports: $Exports<'popmotion/lib/index'>;
}
declare module 'popmotion/lib/input/listen/index.js' {
  declare module.exports: $Exports<'popmotion/lib/input/listen/index'>;
}
declare module 'popmotion/lib/input/listen/types.js' {
  declare module.exports: $Exports<'popmotion/lib/input/listen/types'>;
}
declare module 'popmotion/lib/input/multitouch/index.js' {
  declare module.exports: $Exports<'popmotion/lib/input/multitouch/index'>;
}
declare module 'popmotion/lib/input/pointer/index.js' {
  declare module.exports: $Exports<'popmotion/lib/input/pointer/index'>;
}
declare module 'popmotion/lib/input/pointer/mouse.js' {
  declare module.exports: $Exports<'popmotion/lib/input/pointer/mouse'>;
}
declare module 'popmotion/lib/input/pointer/types.js' {
  declare module.exports: $Exports<'popmotion/lib/input/pointer/types'>;
}
declare module 'popmotion/lib/input/pointer/utils.js' {
  declare module.exports: $Exports<'popmotion/lib/input/pointer/utils'>;
}
declare module 'popmotion/lib/observer/index.js' {
  declare module.exports: $Exports<'popmotion/lib/observer/index'>;
}
declare module 'popmotion/lib/observer/types.js' {
  declare module.exports: $Exports<'popmotion/lib/observer/types'>;
}
declare module 'popmotion/lib/reactions/index.js' {
  declare module.exports: $Exports<'popmotion/lib/reactions/index'>;
}
declare module 'popmotion/lib/reactions/multicast.js' {
  declare module.exports: $Exports<'popmotion/lib/reactions/multicast'>;
}
declare module 'popmotion/lib/reactions/types.js' {
  declare module.exports: $Exports<'popmotion/lib/reactions/types'>;
}
declare module 'popmotion/lib/reactions/value.js' {
  declare module.exports: $Exports<'popmotion/lib/reactions/value'>;
}
declare module 'popmotion/lib/transformers.js' {
  declare module.exports: $Exports<'popmotion/lib/transformers'>;
}
declare module 'popmotion/rollup.config.js' {
  declare module.exports: $Exports<'popmotion/rollup.config'>;
}
