// flow-typed signature: 7806909bb93c286e8c0df440adae2ee6
// flow-typed version: <<STUB>>/react-albus_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-albus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-albus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-albus/lib/components/createWizardComponent' {
  declare module.exports: any;
}

declare module 'react-albus/lib/components/Steps' {
  declare module.exports: any;
}

declare module 'react-albus/lib/components/Wizard' {
  declare module.exports: any;
}

declare module 'react-albus/lib/index' {
  declare module.exports: any;
}

declare module 'react-albus/lib/utils/renderCallback' {
  declare module.exports: any;
}

declare module 'react-albus/lib/withWizard' {
  declare module.exports: any;
}

declare module 'react-albus/lib/wizardShape' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-albus/lib/components/createWizardComponent.js' {
  declare module.exports: $Exports<'react-albus/lib/components/createWizardComponent'>;
}
declare module 'react-albus/lib/components/Steps.js' {
  declare module.exports: $Exports<'react-albus/lib/components/Steps'>;
}
declare module 'react-albus/lib/components/Wizard.js' {
  declare module.exports: $Exports<'react-albus/lib/components/Wizard'>;
}
declare module 'react-albus/lib/index.js' {
  declare module.exports: $Exports<'react-albus/lib/index'>;
}
declare module 'react-albus/lib/utils/renderCallback.js' {
  declare module.exports: $Exports<'react-albus/lib/utils/renderCallback'>;
}
declare module 'react-albus/lib/withWizard.js' {
  declare module.exports: $Exports<'react-albus/lib/withWizard'>;
}
declare module 'react-albus/lib/wizardShape.js' {
  declare module.exports: $Exports<'react-albus/lib/wizardShape'>;
}
