// flow-typed signature: 357f898b26aed6258dec4e849dc17d73
// flow-typed version: <<STUB>>/react-date-picker_v^6.10.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-date-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-date-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-date-picker/dist/DateInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/DateInput/DayInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/DateInput/MonthInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/DateInput/NativeInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/DateInput/YearInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/DatePicker' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/Divider' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/entry' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/entry.nostyle' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/shared/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/shared/dates' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/shared/locales' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-date-picker/dist/shared/utils' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/__tests__/DateInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/__tests__/DatePicker' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/DateInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/DateInput/DayInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/DateInput/MonthInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/DateInput/NativeInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/DateInput/YearInput' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/DatePicker' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/Divider' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/entry' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/entry.nostyle' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/shared/__tests__/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/shared/dateFormatter' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/shared/dates' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/shared/locales' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/shared/propTypes' {
  declare module.exports: any;
}

declare module 'react-date-picker/src/shared/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-date-picker/dist/DateInput.js' {
  declare module.exports: $Exports<'react-date-picker/dist/DateInput'>;
}
declare module 'react-date-picker/dist/DateInput/DayInput.js' {
  declare module.exports: $Exports<'react-date-picker/dist/DateInput/DayInput'>;
}
declare module 'react-date-picker/dist/DateInput/MonthInput.js' {
  declare module.exports: $Exports<'react-date-picker/dist/DateInput/MonthInput'>;
}
declare module 'react-date-picker/dist/DateInput/NativeInput.js' {
  declare module.exports: $Exports<'react-date-picker/dist/DateInput/NativeInput'>;
}
declare module 'react-date-picker/dist/DateInput/YearInput.js' {
  declare module.exports: $Exports<'react-date-picker/dist/DateInput/YearInput'>;
}
declare module 'react-date-picker/dist/DatePicker.js' {
  declare module.exports: $Exports<'react-date-picker/dist/DatePicker'>;
}
declare module 'react-date-picker/dist/Divider.js' {
  declare module.exports: $Exports<'react-date-picker/dist/Divider'>;
}
declare module 'react-date-picker/dist/entry.js' {
  declare module.exports: $Exports<'react-date-picker/dist/entry'>;
}
declare module 'react-date-picker/dist/entry.nostyle.js' {
  declare module.exports: $Exports<'react-date-picker/dist/entry.nostyle'>;
}
declare module 'react-date-picker/dist/shared/dateFormatter.js' {
  declare module.exports: $Exports<'react-date-picker/dist/shared/dateFormatter'>;
}
declare module 'react-date-picker/dist/shared/dates.js' {
  declare module.exports: $Exports<'react-date-picker/dist/shared/dates'>;
}
declare module 'react-date-picker/dist/shared/locales.js' {
  declare module.exports: $Exports<'react-date-picker/dist/shared/locales'>;
}
declare module 'react-date-picker/dist/shared/propTypes.js' {
  declare module.exports: $Exports<'react-date-picker/dist/shared/propTypes'>;
}
declare module 'react-date-picker/dist/shared/utils.js' {
  declare module.exports: $Exports<'react-date-picker/dist/shared/utils'>;
}
declare module 'react-date-picker/src/__tests__/DateInput.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/__tests__/DateInput'>;
}
declare module 'react-date-picker/src/__tests__/DatePicker.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/__tests__/DatePicker'>;
}
declare module 'react-date-picker/src/DateInput.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/DateInput'>;
}
declare module 'react-date-picker/src/DateInput/DayInput.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/DateInput/DayInput'>;
}
declare module 'react-date-picker/src/DateInput/MonthInput.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/DateInput/MonthInput'>;
}
declare module 'react-date-picker/src/DateInput/NativeInput.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/DateInput/NativeInput'>;
}
declare module 'react-date-picker/src/DateInput/YearInput.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/DateInput/YearInput'>;
}
declare module 'react-date-picker/src/DatePicker.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/DatePicker'>;
}
declare module 'react-date-picker/src/Divider.jsx' {
  declare module.exports: $Exports<'react-date-picker/src/Divider'>;
}
declare module 'react-date-picker/src/entry.js' {
  declare module.exports: $Exports<'react-date-picker/src/entry'>;
}
declare module 'react-date-picker/src/entry.nostyle.js' {
  declare module.exports: $Exports<'react-date-picker/src/entry.nostyle'>;
}
declare module 'react-date-picker/src/shared/__tests__/dateFormatter.js' {
  declare module.exports: $Exports<'react-date-picker/src/shared/__tests__/dateFormatter'>;
}
declare module 'react-date-picker/src/shared/dateFormatter.js' {
  declare module.exports: $Exports<'react-date-picker/src/shared/dateFormatter'>;
}
declare module 'react-date-picker/src/shared/dates.js' {
  declare module.exports: $Exports<'react-date-picker/src/shared/dates'>;
}
declare module 'react-date-picker/src/shared/locales.js' {
  declare module.exports: $Exports<'react-date-picker/src/shared/locales'>;
}
declare module 'react-date-picker/src/shared/propTypes.js' {
  declare module.exports: $Exports<'react-date-picker/src/shared/propTypes'>;
}
declare module 'react-date-picker/src/shared/utils.js' {
  declare module.exports: $Exports<'react-date-picker/src/shared/utils'>;
}
