// flow-typed signature: 9635efd1dbb34769bbd33b7f30460cbe
// flow-typed version: <<STUB>>/react-id-swiper_v^1.6.8/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-id-swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-id-swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-id-swiper/__tests__/ReactIdSwiper.test' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/custom' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/index' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/react-id-swiper.custom' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/react-id-swiper.custom.min' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/react-id-swiper' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/react-id-swiper.min' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/swiper/custom' {
  declare module.exports: any;
}

declare module 'react-id-swiper/lib/utils' {
  declare module.exports: any;
}

declare module 'react-id-swiper/src/custom' {
  declare module.exports: any;
}

declare module 'react-id-swiper/src/index' {
  declare module.exports: any;
}

declare module 'react-id-swiper/src/swiper/custom' {
  declare module.exports: any;
}

declare module 'react-id-swiper/src/utils' {
  declare module.exports: any;
}

declare module 'react-id-swiper/test-setup' {
  declare module.exports: any;
}

declare module 'react-id-swiper/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-id-swiper/__tests__/ReactIdSwiper.test.js' {
  declare module.exports: $Exports<'react-id-swiper/__tests__/ReactIdSwiper.test'>;
}
declare module 'react-id-swiper/lib/custom.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/custom'>;
}
declare module 'react-id-swiper/lib/index.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/index'>;
}
declare module 'react-id-swiper/lib/react-id-swiper.custom.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/react-id-swiper.custom'>;
}
declare module 'react-id-swiper/lib/react-id-swiper.custom.min.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/react-id-swiper.custom.min'>;
}
declare module 'react-id-swiper/lib/react-id-swiper.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/react-id-swiper'>;
}
declare module 'react-id-swiper/lib/react-id-swiper.min.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/react-id-swiper.min'>;
}
declare module 'react-id-swiper/lib/swiper/custom.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/swiper/custom'>;
}
declare module 'react-id-swiper/lib/utils.js' {
  declare module.exports: $Exports<'react-id-swiper/lib/utils'>;
}
declare module 'react-id-swiper/src/custom.js' {
  declare module.exports: $Exports<'react-id-swiper/src/custom'>;
}
declare module 'react-id-swiper/src/index.js' {
  declare module.exports: $Exports<'react-id-swiper/src/index'>;
}
declare module 'react-id-swiper/src/swiper/custom.js' {
  declare module.exports: $Exports<'react-id-swiper/src/swiper/custom'>;
}
declare module 'react-id-swiper/src/utils.js' {
  declare module.exports: $Exports<'react-id-swiper/src/utils'>;
}
declare module 'react-id-swiper/test-setup.js' {
  declare module.exports: $Exports<'react-id-swiper/test-setup'>;
}
declare module 'react-id-swiper/webpack.config.js' {
  declare module.exports: $Exports<'react-id-swiper/webpack.config'>;
}
