// flow-typed signature: c4a135dc7988d09ecd5f8640c4594613
// flow-typed version: <<STUB>>/react-perf-devtool_v^3.0.7/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-perf-devtool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-perf-devtool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-perf-devtool/lib/devtool-hook' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/Buttons' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/ComponentTime' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/ErrorComponent' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/Graphics' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/Measures' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/Metrics' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/ProgressLoader' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/ReactPerfDevtool' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/Stats' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/theme' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/util' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/hook' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/index' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/npm/hook' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/commitChanges' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/generate' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/hostEffects' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/lifecycle' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/math' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/parse' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/parseMeasures' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/totalTime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-perf-devtool/index' {
  declare module.exports: $Exports<'react-perf-devtool'>;
}
declare module 'react-perf-devtool/index.js' {
  declare module.exports: $Exports<'react-perf-devtool'>;
}
declare module 'react-perf-devtool/lib/devtool-hook.js' {
  declare module.exports: $Exports<'react-perf-devtool/lib/devtool-hook'>;
}
declare module 'react-perf-devtool/src/extension/components/Buttons.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/Buttons'>;
}
declare module 'react-perf-devtool/src/extension/components/ComponentTime.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/ComponentTime'>;
}
declare module 'react-perf-devtool/src/extension/components/ErrorComponent.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/ErrorComponent'>;
}
declare module 'react-perf-devtool/src/extension/components/Graphics.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/Graphics'>;
}
declare module 'react-perf-devtool/src/extension/components/Measures.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/Measures'>;
}
declare module 'react-perf-devtool/src/extension/components/Metrics.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/Metrics'>;
}
declare module 'react-perf-devtool/src/extension/components/ProgressLoader.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/ProgressLoader'>;
}
declare module 'react-perf-devtool/src/extension/components/ReactPerfDevtool.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/ReactPerfDevtool'>;
}
declare module 'react-perf-devtool/src/extension/components/Stats.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/Stats'>;
}
declare module 'react-perf-devtool/src/extension/theme.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/theme'>;
}
declare module 'react-perf-devtool/src/extension/util.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/util'>;
}
declare module 'react-perf-devtool/src/hook.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/hook'>;
}
declare module 'react-perf-devtool/src/index.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/index'>;
}
declare module 'react-perf-devtool/src/npm/hook.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/npm/hook'>;
}
declare module 'react-perf-devtool/src/shared/commitChanges.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/commitChanges'>;
}
declare module 'react-perf-devtool/src/shared/generate.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/generate'>;
}
declare module 'react-perf-devtool/src/shared/hostEffects.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/hostEffects'>;
}
declare module 'react-perf-devtool/src/shared/lifecycle.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/lifecycle'>;
}
declare module 'react-perf-devtool/src/shared/math.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/math'>;
}
declare module 'react-perf-devtool/src/shared/parse.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/parse'>;
}
declare module 'react-perf-devtool/src/shared/parseMeasures.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/parseMeasures'>;
}
declare module 'react-perf-devtool/src/shared/totalTime.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/totalTime'>;
}
