// flow-typed signature: b9bfb36582f4f0e9915c12ee46adaf72
// flow-typed version: <<STUB>>/react-axe_v^3.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-axe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-axe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-axe/after' {
  declare module.exports: any;
}

declare module 'react-axe/cypress/integration/index-test' {
  declare module.exports: any;
}

declare module 'react-axe/example/src/example' {
  declare module.exports: any;
}

declare module 'react-axe/example/src/globalHeader' {
  declare module.exports: any;
}

declare module 'react-axe/example/src/service' {
  declare module.exports: any;
}

declare module 'react-axe/example/src/serviceChooser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-axe/after.js' {
  declare module.exports: $Exports<'react-axe/after'>;
}
declare module 'react-axe/cypress/integration/index-test.js' {
  declare module.exports: $Exports<'react-axe/cypress/integration/index-test'>;
}
declare module 'react-axe/example/src/example.js' {
  declare module.exports: $Exports<'react-axe/example/src/example'>;
}
declare module 'react-axe/example/src/globalHeader.js' {
  declare module.exports: $Exports<'react-axe/example/src/globalHeader'>;
}
declare module 'react-axe/example/src/service.js' {
  declare module.exports: $Exports<'react-axe/example/src/service'>;
}
declare module 'react-axe/example/src/serviceChooser.js' {
  declare module.exports: $Exports<'react-axe/example/src/serviceChooser'>;
}
declare module 'react-axe/index' {
  declare module.exports: $Exports<'react-axe'>;
}
declare module 'react-axe/index.js' {
  declare module.exports: $Exports<'react-axe'>;
}
