// flow-typed signature: d5215b4e1c7ce51d57f1eefe5a39e020
// flow-typed version: <<STUB>>/react-sanfona_v^1.4.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sanfona'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sanfona' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sanfona/dist-modules/Accordion/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/Accordion/utils' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/AccordionItem/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/AccordionItemBody/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/AccordionItemTitle/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist-modules/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/dist/react-sanfona' {
  declare module.exports: any;
}

declare module 'react-sanfona/page/bundle' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/Accordion/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/Accordion/utils' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/AccordionItem/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/AccordionItemBody/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/AccordionItemTitle/index' {
  declare module.exports: any;
}

declare module 'react-sanfona/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sanfona/dist-modules/Accordion/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/Accordion/index'>;
}
declare module 'react-sanfona/dist-modules/Accordion/utils.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/Accordion/utils'>;
}
declare module 'react-sanfona/dist-modules/AccordionItem/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/AccordionItem/index'>;
}
declare module 'react-sanfona/dist-modules/AccordionItemBody/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/AccordionItemBody/index'>;
}
declare module 'react-sanfona/dist-modules/AccordionItemTitle/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/AccordionItemTitle/index'>;
}
declare module 'react-sanfona/dist-modules/index.js' {
  declare module.exports: $Exports<'react-sanfona/dist-modules/index'>;
}
declare module 'react-sanfona/dist/react-sanfona.js' {
  declare module.exports: $Exports<'react-sanfona/dist/react-sanfona'>;
}
declare module 'react-sanfona/page/bundle.js' {
  declare module.exports: $Exports<'react-sanfona/page/bundle'>;
}
declare module 'react-sanfona/src/Accordion/index.js' {
  declare module.exports: $Exports<'react-sanfona/src/Accordion/index'>;
}
declare module 'react-sanfona/src/Accordion/utils.js' {
  declare module.exports: $Exports<'react-sanfona/src/Accordion/utils'>;
}
declare module 'react-sanfona/src/AccordionItem/index.js' {
  declare module.exports: $Exports<'react-sanfona/src/AccordionItem/index'>;
}
declare module 'react-sanfona/src/AccordionItemBody/index.js' {
  declare module.exports: $Exports<'react-sanfona/src/AccordionItemBody/index'>;
}
declare module 'react-sanfona/src/AccordionItemTitle/index.js' {
  declare module.exports: $Exports<'react-sanfona/src/AccordionItemTitle/index'>;
}
declare module 'react-sanfona/src/index.js' {
  declare module.exports: $Exports<'react-sanfona/src/index'>;
}
