// flow-typed signature: 3543f07abed0f31e72389a262d10ed4d
// flow-typed version: <<STUB>>/@tedconf/react-show-more_v^1.1.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tedconf/react-show-more'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tedconf/react-show-more' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tedconf/react-show-more/dist/@tedconf/react-show-more.cjs' {
  declare module.exports: any;
}

declare module '@tedconf/react-show-more/dist/@tedconf/react-show-more.es' {
  declare module.exports: any;
}

declare module '@tedconf/react-show-more/dist/@tedconf/react-show-more' {
  declare module.exports: any;
}

declare module '@tedconf/react-show-more/dist/react-show-more.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tedconf/react-show-more/dist/@tedconf/react-show-more.cjs.js' {
  declare module.exports: $Exports<'@tedconf/react-show-more/dist/@tedconf/react-show-more.cjs'>;
}
declare module '@tedconf/react-show-more/dist/@tedconf/react-show-more.es.js' {
  declare module.exports: $Exports<'@tedconf/react-show-more/dist/@tedconf/react-show-more.es'>;
}
declare module '@tedconf/react-show-more/dist/@tedconf/react-show-more.js' {
  declare module.exports: $Exports<'@tedconf/react-show-more/dist/@tedconf/react-show-more'>;
}
declare module '@tedconf/react-show-more/dist/react-show-more.min.js' {
  declare module.exports: $Exports<'@tedconf/react-show-more/dist/react-show-more.min'>;
}
